[project]
name = "fr-mcmc"
version = "0.1.0"
description = "MCMC analysis of f(R) background cosmologies with various datasets"
authors = [{ name = "Matías Leizerovich" }]
readme = "README.md"
requires-python = ">=3.7"

dependencies = [
  "numpy>=1.19",
  "scipy>=1.5",
  "matplotlib>=3.1",
  "click>=8.0",
  "pyyaml>=5.3",
  "python-box>=5.0",
  "emcee>=3.0",
  "pandas>=1.1",
  "tqdm>=4.50",
]

[project.urls]
"Source" = "https://github.com/matiasleize/fR-MCMC"

[project.scripts]
fr-mcmc = "fr_mcmc.run:main_cli"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
