USE_SN: True
USE_CC: True
USE_BAO: False
USE_AGN: False
USE_H0: False

MODEL: 'HS' #Choose between 'LCDM', 'HS' or 'EXP'
WITNESS_NUM: 24 #Suggestion: (model_number) + (datasets_number) 
FIXED_PARAMS: 0 #For now only 0
LOG_LIKELIHOOD_INDEX: 4 #Could be 32 or 4
NUM_WALKERS: 12
MAX_SAMPLES: 2000000
WITNESS_FREQ: 100

#For now only flat priors
M_PRIOR: [-22, -18]
OMEGA_M_PRIOR: [0.01, 0.5]
B_PRIOR: [0, 3] #Only read if MODEL is 'HS' or 'EXP'
H0_PRIOR: [60, 80]

#For the mean values if needed:
GUEST: [-19.352, 0.22, 0.5, 70.87]
BOUNDS: [[-25, -18], [0.1, 0.5], [0.1, 1], [64, 80]]

#Other things that are not in use:
#DATA_PATH: './data'